version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=highload
      - POSTGRES_USER=high_user
      - POSTGRES_PASSWORD=high_user
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U high_user -d highload" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

#  liquibase:
#    image: liquibase/liquibase:4.9.1
#    container_name: liquibase
#    depends_on:
#      db:
#        condition: service_healthy
#    volumes:
#      - ./src/main/resources/db/changelog/:/liquibase/db/changelog/
#    command: [
#      /liquibase/liquibase,
#      --username=high_user,
#      --password=high_user,
#      --driver=org.postgresql.Driver,
#      --url=jdbc:postgresql://db:5432/highload,
#      --changeLogFile=db/changelog/db.changelog-master.yaml,
#      update,
#    ]
  app:
    image: 'highload.jar'
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - HOST=db
      - PORT=5432
      - NAME=highload
      - USER=high_user
      - PASS=high_user
